web:
  image: nginx:latest
  ports:
    - "80:80"
  volumes:
    - ./code:/code 
    - ./site.conf:/etc/nginx/conf.d/site.conf
  links:
    - php
    - db

php:
  image: flkone/php7-fpm-pdo:latest
  volumes:
    - ./code:/code    
  links:
    - db    
db:
  image: mariadb
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: defaultuserdb
    MYSQL_PASSWORD: defaultpwddb
    MYSQL_DATABASE: defaultdb
  ports: