version: 2
jobs:
  build:
    # Actually, this `docker` keyword means your CircleCI build will be launched in a docker
    # container instead of a Linux VM.
    #machine: true # Use a Linux VM instead of docker environment.
    docker:      
      - image: docker:stable-git #circleci/node:7.10 # Specify the version you desire here.  
    #working_directory: ~/repo # Default working directory, where your project will be cloned  .
    steps:
      - checkout # Add a checkout of the repository.
      # ... steps for building/testing app ...

      #- run
      #  name: Build Docker image
      #  command: docker build -t raniazy/bot@CIRCLE_SHA1 . 

      # When setup_remote_docker executes, a remote environment will be created, and your current
      # primary container will be configured to use it. Then, any docker-related commands you use
      #will be safely executed in this new environment.
      - setup_remote_docker:
          reusable: true
          exclusive: true

      - run:
          name: Connect to Docker Hub
          command: apk update && apk add curl curl-dev bash

      #    version: 17.05.0-ce
      - run:
          name: Connect to Docker Hub
          command: docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"

      - deploy:
          name: Publish application to docker hub
          branch: master
          command: $DOCKER_HUB_TRIGGER
