# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.14 
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4


    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Dependencies 1
          command: yarn install --frozen-lockfile




      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar

      - deploy:
          name: Publish application to docker hub
          command: $DOCKER_HUB_TRIGGER

      - save_cache:
          name: Save Yarn Package Cache
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: chmod sh permissions
          command: chmod +x ./scripts/test

      - run:
          name: chmod js permissions
          command: chmod u+x ./test/test.js

      - run: 
          name: Run sh-tests
          command: yarn sh-tests

      - run: 
          name: Run mocha-tests
          command: yarn run test



