version: 2
jobs:
  build:
    docker:
      - image: golang:1.6.4-jessie   # (1)
    working_directory: /go/src/github.com/CircleCI-Public/circleci-demo-docker
    steps:
      - checkout
      # ... steps for building/testing app ...

      # When setup_remote_docker executes, a remote environment will be created, and your current
      # primary container will be configured to use it. Then, any docker-related commands you use
      #will be safely executed in this new environment.
      - setup_remote_docker:
          version: 17.05.0-ce
