version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run:
          name: Build application Docker image
          command: docker build -t $ECR_REPO:0.1 .
   