version: 2
jobs:
  build:
    # Actually, this `docker` keyword means your CircleCI build will be launched in a docker
    # container instead of a Linux VM.
    #machine: true # Use a Linux VM instead of docker environment.
    docker:      
      - image: docker:17.05.0-ce-git #docker:stable-git #circleci/node:7.10 # Specify the version you desire here.  
    #working_directory: ~/repo # Default working directory, where your project will be cloned  .
    steps:
      - checkout # Add a checkout of the repository.

      # When setup_remote_docker executes, a remote environment will be created, and your current
      # primary container will be configured to use it. Then, any docker-related commands you use
      #will be safely executed in this new environment.
      - setup_remote_docker:

      - run:
          name: Prepare qemu 
          command: docker run --rm --privileged multiarch/qemu-user-static:register --reset

      - run:
          name: This creates a Docker image, which we’re going to tag using -t so it has a friendly name.
          command: docker build -t pereric/iprincipnufinance:latest .

      - run:
          name: Connect to Docker Hub
          command: docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"

      - deploy:
          name: Publish application to docker hub
          command: docker push pereric/iprincipnufinance:latest
